version: '3.8'

services:
    app:
        image: ghcr.io/mixdrinks/site:${GIT_COMMIT_SHA:-latest}
        environment:
            - NUXT_PUBLIC_DOMAIN=https://mixdrinks.org
            - NUXT_PUBLIC_GIT_COMMIT_SHA=${GIT_COMMIT_SHA}
            - NUXT_MONGO_URI=${MONGO_URI}
        deploy:
            update_config:
                order: start-first
        networks:
            - infra_reverse-proxy
            - infra_mongo-rs-net

networks:
    infra_reverse-proxy:
        external: true
    infra_mongo-rs-net:
        external: true
