version: '3.8'

services:
    app:
        image: ghcr.io/mixdrinks/site:${GIT_COMMIT_SHA:-latest}
        ports:
            - '40001:3000'
        environment:
            - NUXT_PUBLIC_SECRET_FILE=/run/secrets/mixdrinks
            - NUXT_DOMAIN=https://mixdrinks.org
        secrets:
            - mixdrinks
        deploy:
            update_config:
                order: start-first
        networks:
            - infra_reverse-proxy
secrets:
    mixdrinks:
        external: true

networks:
    infra_reverse-proxy:
        external: true
