name: Branch build

on:
  push:
    branches:
      - '*'

env:
  BRANCH_NAME: ${{ github.ref##*/ }}

jobs:
  branch_build:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        run: echo "Branch name is $BRANCH_NAME"
        env:
          GITHUB_REF: ${{ github.ref }}
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/mixdrinks-web:${{env.BRANCH_NAME}}
