name: End-to-end tests
on: pull_request
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Run Tests
        id: run_tests
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: npm run dev
          wait-on: "http://localhost:8080"
          record: true
        env: 
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
          GITHUB_HEAD_REF: ${{github.head_ref}}
          GITHUB_REF: ${{github.ref}}
  telegram-post-message:
    if: ${{ always() }}
    runs-on: ubuntu-22.04
    needs: [cypress-run]
    steps:
      - name: send telegram message after tests run
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            *Cypres Tests for MixDrinks web results*
            *Branch:* ${{ github.ref }}
            *Repository:* ${{ github.repository }}
            *Results:* https://cloud.cypress.io/projects/oxq4yv/runs
