name: End-to-end tests
on: pull_request
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Run Tests
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: npm run dev
          wait-on: "http://localhost:8080"
          record: true
        env: 
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
          GITHUB_HEAD_REF: ${{github.head_ref}}
          GITHUB_REF: ${{github.ref}}
      - name: send telegram message after tests run
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            *Cypres Tests results*
            Application: MixDrinks          
            Branch: *${{ github.ref }}*
            Repository: *${{ github.repository }}*
            Owner: *${{ github.repository_owner }}*
            Results: https://cloud.cypress.io/organizations/dfa8a8f7-f5ab-49af-aad0-a5d3b64f89c9/projects
