name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          npm ci
          npm run dev

      - name: Run Tests
        uses: cypress-io/github-action@v5
        with:
          install: false
          wait-on: 'http://localhost:8080/'
          config: baseUrl=http://localhost:8080/